version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: csr_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csr_funding_portal
      MYSQL_USER: csr_user
      MYSQL_PASSWORD: csr_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: