"""add confidence score to chat query audit

Revision ID: 37b963ddfd8b
Revises: dcd8e655083b
Create Date: 2026-08-26 13:56:45.543036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b963ddfd8b'
down_revision = 'dcd8e655083b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_query_audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_query_audits', schema=None) as batch_op:
        batch_op.drop_column('confidence_score')

    # ### end Alembic commands ###
