"""add conversation last generated sql column

Revision ID: 46381a0ff214
Revises: d98f587c0dab
Create Date: 2026-08-26 14:31:27.092939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46381a0ff214'
down_revision = 'd98f587c0dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_generated_sql', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('last_generated_sql')

    # ### end Alembic commands ###
