"""add message feedback and chat promoted examples table

Revision ID: d98f587c0dab
Revises: 37b963ddfd8b
Create Date: 2026-08-26 14:13:38.983141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98f587c0dab'
down_revision = '37b963ddfd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_promoted_examples',
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    op.drop_table('chat_promoted_examples')
    # ### end Alembic commands ###
