"""add chat query cache table and message chat columns

Revision ID: dcd8e655083b
Revises: e14ef5e43437
Create Date: 2026-08-26 13:43:34.353865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd8e655083b'
down_revision = 'e14ef5e43437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_query_cache',
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_query_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_query_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_query_cache_question_hash'), ['question_hash'], unique=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sql_generated', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('table_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('response_source', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('response_source')
        batch_op.drop_column('table_data')
        batch_op.drop_column('sql_generated')

    with op.batch_alter_table('chat_query_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_query_cache_question_hash'))
        batch_op.drop_index(batch_op.f('ix_chat_query_cache_expires_at'))

    op.drop_table('chat_query_cache')
    # ### end Alembic commands ###
