"""add chat query audit and failed question tables

Revision ID: e14ef5e43437
Revises: a1b2c3d4e5f6
Create Date: 2026-08-26 13:35:42.269169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14ef5e43437'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_failed_questions',
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('failure_stage', sa.String(length=30), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_sql_attempted', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_failed_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_failed_questions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_failed_questions_message_id'), ['message_id'], unique=False)

    op.create_table('chat_query_audits',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=False),
    sa.Column('response_source', sa.String(length=20), nullable=False),
    sa.Column('sql_generated', sa.Text(), nullable=True),
    sa.Column('sql_attempt_count', sa.Integer(), nullable=True),
    sa.Column('gemini_model', sa.String(length=64), nullable=True),
    sa.Column('sql_gen_latency_ms', sa.Integer(), nullable=True),
    sa.Column('narrative_gen_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_query_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_query_audits_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_query_audits_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_query_audits_normalized_question'), ['normalized_question'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_query_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_query_audits_normalized_question'))
        batch_op.drop_index(batch_op.f('ix_chat_query_audits_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_query_audits_conversation_id'))

    op.drop_table('chat_query_audits')
    with op.batch_alter_table('chat_failed_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_failed_questions_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_failed_questions_conversation_id'))

    op.drop_table('chat_failed_questions')
    # ### end Alembic commands ###
