"""add region and financial year

Revision ID: e35f815113d7
Revises: e6d2d5720806
Create Date: 2026-07-14 07:45:59.821427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e35f815113d7'
down_revision = 'e6d2d5720806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    tables = set(sa.inspect(bind).get_table_names())
    project_columns = {c["name"] for c in sa.inspect(bind).get_columns("projects")}

    # donors/risks and the raised_amount/utilized_amount columns below were
    # originally created out-of-band (never tracked by an earlier Alembic
    # migration), so this migration only alters their type. Guard each step
    # so `flask db upgrade` also reaches a working schema on a fresh DB that
    # never had those out-of-band changes, and so a retry after a failed
    # partial run (MySQL DDL isn't transactional) doesn't try to redo work
    # that already landed.
    if "donors" not in tables:
        op.create_table('donors',
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('focus_area', sa.String(length=150), nullable=True),
        sa.Column('likelihood', sa.Integer(), nullable=True),
        sa.Column('last_contact', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=30), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if "risks" not in tables:
        op.create_table('risks',
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('level', sa.String(length=30), nullable=True),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('action', sa.String(length=150), nullable=True),
        sa.Column('icon', sa.String(length=30), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    with op.batch_alter_table('projects', schema=None) as batch_op:
        if "region" not in project_columns:
            batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))

        if "financial_year" not in project_columns:
            batch_op.add_column(sa.Column('financial_year', sa.String(length=20), nullable=True))

        if "beneficiaries_reached" not in project_columns:
            batch_op.add_column(sa.Column('beneficiaries_reached', sa.Integer(), nullable=True))

        if "raised_amount" not in project_columns:
            batch_op.add_column(sa.Column('raised_amount', sa.Float(), nullable=True))
        else:
            batch_op.alter_column('raised_amount',
                   existing_type=mysql.DECIMAL(precision=12, scale=2),
                   type_=sa.Float(),
                   existing_nullable=True)

        if "utilized_amount" not in project_columns:
            batch_op.add_column(sa.Column('utilized_amount', sa.Float(), nullable=True))
        else:
            batch_op.alter_column('utilized_amount',
                   existing_type=mysql.DECIMAL(precision=12, scale=2),
                   type_=sa.Float(),
                   existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('utilized_amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('raised_amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=True)
        batch_op.drop_column('beneficiaries_reached')
        batch_op.drop_column('financial_year')
        batch_op.drop_column('region')

    op.drop_table('risks')
    op.drop_table('donors')
    # ### end Alembic commands ###
